name: TF init
on: 
  push:
  workflow_dispatch:
    
jobs:
  Deploy_with_terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
    - name: Init terraform
      run: terraform init
    - name: Terraform plan
      id: plan
      run: terraform plan -no-color -lock=false
    - name: Terraform apply
      id: apply 
      run: terraform apply -auto-approve -lock=false

