name: Regenerate terraform infra
on: workflow_dispatch
  
  #push:
  #  branches:    
  #    - 'main'

jobs:
  Destroy_current_terraform_infra:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform init
      run: terraform init
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Terraform plan
      run: terraform plan -no-color -destroy
    - name: Terraform apply 
      run: terraform destroy -auto-approve
    - name: Commit lock
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "commit TF lock"
  Create_infra_with_terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
    - name: Init terraform
      run: terraform init
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Terraform plan
      id: plan
      run: terraform plan -no-color
    - name: Terraform apply
      id: apply 
      run: terraform apply -auto-approve
    - name: Commit lock
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "commit TF lock"